import {
    CART as SOURCE_CART,
    CART_EDITING,
    CART_OVERLAY,
    CATEGORY,
    CHECKOUT,
    CHECKOUT_ACCOUNT,
    CHECKOUT_SUCCESS,
    CMS_PAGE,
    CONTACT_US,
    CUSTOMER_ACCOUNT,
    CUSTOMER_ACCOUNT_PAGE,
    CUSTOMER_ORDER,
    CUSTOMER_SUB_ACCOUNT,
    CUSTOMER_WISHLIST,
    FILTER,
    HOME_PAGE,
    MENU as SOURCE_MENU,
    MENU_SUBCATEGORY,
    MY_ACCOUNT as SOURCE_MY_ACCOUNT,
    NO_MATCH,
    PDP,
    POPUP,
    PRODUCT_COMPARE,
    SEARCH
} from 'SourceComponent/Header/Header.config';

export {
    PDP,
    POPUP,
    CATEGORY,
    CUSTOMER_ACCOUNT,
    CUSTOMER_SUB_ACCOUNT,
    CUSTOMER_ACCOUNT_PAGE,
    CUSTOMER_WISHLIST,
    CUSTOMER_ORDER,
    HOME_PAGE,
    MENU_SUBCATEGORY,
    SEARCH,
    FILTER,
    CART_OVERLAY,
    CART_EDITING,
    CHECKOUT,
    CHECKOUT_SUCCESS,
    CHECKOUT_ACCOUNT,
    CMS_PAGE,
    NO_MATCH,
    CONTACT_US,
    PRODUCT_COMPARE
};

// TODO: implement MENU
export const MENU = SOURCE_MENU;

// TODO: implement CART
export const CART = SOURCE_CART;

// TODO: implement MY_ACCOUNT
export const MY_ACCOUNT = SOURCE_MY_ACCOUNT;
